application: nico-nico
version: 1
runtime: python
api_version: 1

handlers:
- url: /clientaccesspolicy.xml
  static_files: clientaccesspolicy.xml
  upload: clientaccesspolicy.xml

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /(.*\.xap)
  static_files: slight/\1
  upload: slight/(.*\.xap)

- url: /(.*\.xaml)
  static_files: slight/\1
  upload: slight/(.*\.xaml)

- url: /.*
  script: main.py 